name: Windows Build (Artifact)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        uses: aseprite/get-ninja@main

      - name: Build Aseprite
        shell: bash
        run: |
          bash build.sh --auto --norun

      - name: Download OpenSSL DLLs
        shell: bash
        run: |
          cd build/bin
          curl -L -o libcrypto-1_1.dll https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/libcrypto-1_1-x64.dll
          curl -L -o libssl-1_1.dll https://github.com/openssl/openssl/releases/download/OpenSSL_1_1_1w/libssl-1_1-x64.dll

      - name: Upload Aseprite.exe with DLLs
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-exe
          path: |
            build/bin/aseprite.exe
            build/bin/libcrypto-1_1.dll
            build/bin/libssl-1_1.dll
